logging:
  config: classpath:log4j2.xml
spring:
  main:
    web-application-type: NONE
camel:
  rabbit-mq:
    host: "localhost"
    port: 5672
    virtual-host: "user"
    username: "user"
    password: "user"
    queue-input-endpoint: "rabbitmq://user?queue=inputqueue&autoDelete=false&connectionFactory=#rabbitConnectionFactory"
    queue-output-invoice-endpoint: "rabbitmq://invoice?queue=outputinvoice&autoDelete=false"
    queue-output-order-endpoint: "rabbitmq://order?queue=outputorder&autoDelete=false"

